import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const questions = [
  // ========== MATHEMATICS ==========
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is the value of π (pi) rounded to 2 decimal places?",
    options: ["3.14", "3.41", "3.12", "3.16"],
    answer: "3.14",
    explanation: "Pi (π) is approximately 3.14159..., which rounds to 3.14.",
    points: 10,
    timeLimit: 20,
    tags: ["constants", "geometry"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is 15% of 200?",
    options: ["30", "25", "35", "20"],
    answer: "30",
    explanation: "15% of 200 = (15/100) × 200 = 0.15 × 200 = 30.",
    points: 10,
    timeLimit: 20,
    tags: ["percentages", "arithmetic"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is the derivative of f(x) = x³ + 2x?",
    options: ["3x² + 2", "3x² + 2x", "x² + 2", "3x + 2"],
    answer: "3x² + 2",
    explanation: "Using the power rule: d/dx(x³) = 3x² and d/dx(2x) = 2, so f'(x) = 3x² + 2.",
    points: 20,
    timeLimit: 35,
    tags: ["calculus", "derivatives"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is the sum of angles in a pentagon?",
    options: ["540°", "360°", "720°", "480°"],
    answer: "540°",
    explanation: "Sum of interior angles = (n-2) × 180° = (5-2) × 180° = 540°.",
    points: 20,
    timeLimit: 30,
    tags: ["geometry", "polygons"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "What is the sum of the infinite geometric series 1 + 1/2 + 1/4 + 1/8 + ...?",
    options: ["2", "1.5", "3", "Infinity"],
    answer: "2",
    explanation: "For geometric series with a=1 and r=1/2: S = a/(1-r) = 1/(1-0.5) = 2.",
    points: 30,
    timeLimit: 45,
    tags: ["series", "algebra"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "If log₂(x) = 5, what is x?",
    options: ["32", "25", "10", "16"],
    answer: "32",
    explanation: "log₂(x) = 5 means 2⁵ = x, so x = 32.",
    points: 30,
    timeLimit: 40,
    tags: ["logarithms", "algebra"],
  },
  // ========== SCIENCE ==========
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What is the chemical formula for water?",
    options: ["H₂O", "CO₂", "O₂", "H₂O₂"],
    answer: "H₂O",
    explanation: "Water consists of 2 hydrogen atoms bonded to 1 oxygen atom.",
    points: 10,
    timeLimit: 20,
    tags: ["chemistry", "basics"],
  },
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What planet is closest to the Sun?",
    options: ["Mercury", "Venus", "Earth", "Mars"],
    answer: "Mercury",
    explanation: "Mercury is the first planet from the Sun, at an average distance of ~57.9 million km.",
    points: 10,
    timeLimit: 20,
    tags: ["astronomy", "solar system"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the speed of light in a vacuum?",
    options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
    answer: "3 × 10⁸ m/s",
    explanation: "The speed of light (c) ≈ 299,792,458 m/s ≈ 3 × 10⁸ m/s.",
    points: 20,
    timeLimit: 30,
    tags: ["physics", "constants"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the powerhouse of the cell?",
    options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"],
    answer: "Mitochondria",
    explanation: "Mitochondria produce ATP (energy) through cellular respiration, earning them the nickname 'powerhouse of the cell'.",
    points: 20,
    timeLimit: 25,
    tags: ["biology", "cell biology"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What does the Heisenberg Uncertainty Principle state?",
    options: ["Δx·Δp ≥ ℏ/2", "E = mc²", "F = ma", "PV = nRT"],
    answer: "Δx·Δp ≥ ℏ/2",
    explanation: "Heisenberg's principle states that position and momentum cannot both be precisely measured simultaneously.",
    points: 40,
    timeLimit: 60,
    tags: ["quantum physics", "uncertainty"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What is the atomic number of Gold (Au)?",
    options: ["79", "78", "80", "47"],
    answer: "79",
    explanation: "Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.",
    points: 35,
    timeLimit: 40,
    tags: ["chemistry", "periodic table"],
  },
  // ========== TECHNOLOGY ==========
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does CPU stand for?",
    options: ["Central Processing Unit", "Computer Personal Unit", "Core Processing Unit", "Central Program Utility"],
    answer: "Central Processing Unit",
    explanation: "CPU (Central Processing Unit) is the primary component that executes instructions in a computer.",
    points: 10,
    timeLimit: 20,
    tags: ["hardware", "basics"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does HTML stand for?",
    options: ["HyperText Markup Language", "High-Level Text Machine Language", "HyperTransfer Markup Logic", "Home Tool Markup Language"],
    answer: "HyperText Markup Language",
    explanation: "HTML (HyperText Markup Language) is the standard language for creating web pages.",
    points: 10,
    timeLimit: 20,
    tags: ["web development", "basics"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is the time complexity of binary search on a sorted array?",
    options: ["O(log n)", "O(n)", "O(n²)", "O(1)"],
    answer: "O(log n)",
    explanation: "Binary search halves the search space at each step, resulting in O(log n) time complexity.",
    points: 20,
    timeLimit: 30,
    tags: ["algorithms", "complexity"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is the purpose of a REST API?",
    options: ["Enable communication between client and server", "Store data in a database", "Render HTML pages", "Compile code"],
    answer: "Enable communication between client and server",
    explanation: "REST APIs provide a standardized way for clients and servers to communicate using HTTP methods.",
    points: 20,
    timeLimit: 30,
    tags: ["web development", "APIs"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "In blockchain, what is a Merkle Tree used for?",
    options: ["Efficient verification of large data sets", "Mining new blocks", "Encrypting private keys", "Consensus mechanism"],
    answer: "Efficient verification of large data sets",
    explanation: "Merkle Trees create a hash-based tree structure allowing efficient and secure verification of data.",
    points: 35,
    timeLimit: 45,
    tags: ["blockchain", "data structures"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "What is the difference between TCP and UDP?",
    options: ["TCP is reliable/ordered; UDP is faster but unreliable", "TCP is faster; UDP is reliable", "They are the same protocol", "TCP is for web; UDP is for databases"],
    answer: "TCP is reliable/ordered; UDP is faster but unreliable",
    explanation: "TCP provides guaranteed delivery and ordering. UDP sacrifices reliability for speed, used in streaming/gaming.",
    points: 35,
    timeLimit: 45,
    tags: ["networking", "protocols"],
  },
  // ========== ENGINEERING ==========
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "Ohm's Law states that V = ?",
    options: ["I × R", "I / R", "I + R", "I² × R"],
    answer: "I × R",
    explanation: "Ohm's Law: Voltage (V) = Current (I) × Resistance (R). Fundamental to electrical engineering.",
    points: 10,
    timeLimit: 20,
    tags: ["electrical", "fundamentals"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "What does CAD stand for in engineering?",
    options: ["Computer-Aided Design", "Computer Automated Drawing", "Central Application Design", "Computer Analysis Device"],
    answer: "Computer-Aided Design",
    explanation: "CAD (Computer-Aided Design) is software used to create 2D and 3D models of products and structures.",
    points: 10,
    timeLimit: 20,
    tags: ["design", "tools"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the SI unit of pressure?",
    options: ["Pascal (Pa)", "Newton (N)", "Joule (J)", "Watt (W)"],
    answer: "Pascal (Pa)",
    explanation: "The Pascal (Pa) is the SI unit of pressure, equal to 1 Newton per square meter (N/m²).",
    points: 20,
    timeLimit: 25,
    tags: ["mechanics", "units"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the purpose of a capacitor in a circuit?",
    options: ["Store and release electrical energy", "Resist current flow", "Amplify signals", "Convert AC to DC"],
    answer: "Store and release electrical energy",
    explanation: "Capacitors store electrical energy in an electric field and release it when needed.",
    points: 20,
    timeLimit: 30,
    tags: ["electrical", "components"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "What does the Nyquist theorem state in signal processing?",
    options: ["Sample rate must be at least 2× signal frequency", "Sample rate equals signal frequency", "Signal frequency must be halved", "Bandwidth equals sample rate"],
    answer: "Sample rate must be at least 2× signal frequency",
    explanation: "To accurately reconstruct a signal, the sampling rate must be at least twice the highest frequency present.",
    points: 35,
    timeLimit: 45,
    tags: ["signal processing", "digital"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "In materials science, what is Young's Modulus a measure of?",
    options: ["Material stiffness/elasticity", "Material hardness", "Thermal conductivity", "Electrical resistance"],
    answer: "Material stiffness/elasticity",
    explanation: "Young's Modulus (E) measures a material's stiffness — the ratio of stress to strain in the elastic region.",
    points: 35,
    timeLimit: 45,
    tags: ["materials science", "mechanics"],
  },
];

const achievements = [
  {
    name: "First Steps",
    description: "Complete your first quiz",
    icon: "🎯",
    category: "SCORE",
    condition: { type: "quiz_count", value: 1 },
    xpReward: 50,
    coinsReward: 25,
    rarity: "COMMON",
  },
  {
    name: "Getting Started",
    description: "Complete 10 quizzes",
    icon: "📚",
    category: "SCORE",
    condition: { type: "quiz_count", value: 10 },
    xpReward: 100,
    coinsReward: 50,
    rarity: "COMMON",
  },
  {
    name: "Math Wizard",
    description: "Score 100% on 5 Math quizzes",
    icon: "🧮",
    category: "SUBJECT_MASTERY",
    condition: { type: "perfect_score", value: 5, subject: "MATHEMATICS" },
    xpReward: 200,
    coinsReward: 100,
    rarity: "RARE",
  },
  {
    name: "Science Genius",
    description: "Score 100% on 5 Science quizzes",
    icon: "🔬",
    category: "SUBJECT_MASTERY",
    condition: { type: "perfect_score", value: 5, subject: "SCIENCE" },
    xpReward: 200,
    coinsReward: 100,
    rarity: "RARE",
  },
  {
    name: "On Fire 🔥",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    category: "STREAK",
    condition: { type: "streak", value: 7 },
    xpReward: 300,
    coinsReward: 150,
    rarity: "EPIC",
  },
  {
    name: "Speed Demon",
    description: "Answer a question in under 5 seconds",
    icon: "⚡",
    category: "SPEED",
    condition: { type: "fast_answer", value: 5 },
    xpReward: 150,
    coinsReward: 75,
    rarity: "RARE",
  },
  {
    name: "STEM Legend",
    description: "Reach level 20",
    icon: "👑",
    category: "SPECIAL",
    condition: { type: "level", value: 20 },
    xpReward: 1000,
    coinsReward: 500,
    rarity: "LEGENDARY",
  },
  {
    name: "All-Rounder",
    description: "Play quizzes in all 4 STEM subjects",
    icon: "🌟",
    category: "SPECIAL",
    condition: { type: "all_subjects", value: 4 },
    xpReward: 250,
    coinsReward: 125,
    rarity: "EPIC",
  },
];

async function main() {
  console.log("🌱 Seeding STEMiks database...");

  for (const q of questions) {
    await prisma.question.create({ data: q as any });
  }
  console.log(`✅ Seeded ${questions.length} questions`);

  for (const a of achievements) {
    await prisma.achievement.upsert({
      where: { name: a.name },
      update: {},
      create: a as any,
    });
  }
  console.log(`✅ Seeded ${achievements.length} achievements`);
  console.log("🎉 Database seed complete!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
