import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const questions = [
  // ========== MATHEMATICS (20 QUESTIONS) ==========
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is the value of π (pi) rounded to 2 decimal places?",
    options: ["3.14", "3.41", "3.12", "3.16"],
    answer: "3.14",
    explanation: "Pi (π) is approximately 3.14159..., which rounds to 3.14.",
    points: 10,
    timeLimit: 20,
    tags: ["constants", "geometry"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is 15% of 200?",
    options: ["30", "25", "35", "20"],
    answer: "30",
    explanation: "15% of 200 = (15/100) × 200 = 0.15 × 200 = 30.",
    points: 10,
    timeLimit: 20,
    tags: ["percentages", "arithmetic"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is the derivative of f(x) = x³ + 2x?",
    options: ["3x² + 2", "3x² + 2x", "x² + 2", "3x + 2"],
    answer: "3x² + 2",
    explanation: "Using the power rule: d/dx(x³) = 3x² and d/dx(2x) = 2, so f'(x) = 3x² + 2.",
    points: 20,
    timeLimit: 35,
    tags: ["calculus", "derivatives"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is the sum of angles in a pentagon?",
    options: ["540°", "360°", "720°", "480°"],
    answer: "540°",
    explanation: "Sum of interior angles = (n-2) × 180° = (5-2) × 180° = 540°.",
    points: 20,
    timeLimit: 30,
    tags: ["geometry", "polygons"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "What is the sum of the infinite geometric series 1 + 1/2 + 1/4 + 1/8 + ...?",
    options: ["2", "1.5", "3", "Infinity"],
    answer: "2",
    explanation: "For geometric series with a=1 and r=1/2: S = a/(1-r) = 1/(1-0.5) = 2.",
    points: 30,
    timeLimit: 45,
    tags: ["series", "algebra"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "If log₂(x) = 5, what is x?",
    options: ["32", "25", "10", "16"],
    answer: "32",
    explanation: "log₂(x) = 5 means 2⁵ = x, so x = 32.",
    points: 30,
    timeLimit: 40,
    tags: ["logarithms", "algebra"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is the square root of 144?",
    options: ["12", "14", "10", "16"],
    answer: "12",
    explanation: "√144 = 12 because 12 × 12 = 144.",
    points: 10,
    timeLimit: 20,
    tags: ["roots", "algebra"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is 25 ÷ 5 + 3?",
    options: ["8", "10", "6", "5"],
    answer: "8",
    explanation: "Following order of operations: 25 ÷ 5 = 5, then 5 + 3 = 8.",
    points: 10,
    timeLimit: 20,
    tags: ["arithmetic", "operations"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is the area of a circle with radius 5?",
    options: ["25π", "10π", "50π", "15π"],
    answer: "25π",
    explanation: "Area of circle = πr² = π(5)² = 25π.",
    points: 20,
    timeLimit: 30,
    tags: ["geometry", "circles"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "Solve: 2x + 5 = 13. What is x?",
    options: ["4", "9", "5", "6"],
    answer: "4",
    explanation: "2x + 5 = 13 → 2x = 8 → x = 4.",
    points: 20,
    timeLimit: 30,
    tags: ["algebra", "equations"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "What is the integral of 3x²?",
    options: ["x³ + C", "3x³ + C", "6x + C", "x² + C"],
    answer: "x³ + C",
    explanation: "∫3x² dx = 3 × (x³/3) + C = x³ + C.",
    points: 30,
    timeLimit: 45,
    tags: ["calculus", "integration"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "What is tan(45°)?",
    options: ["1", "0", "√2", "1/√2"],
    answer: "1",
    explanation: "tan(45°) = sin(45°)/cos(45°) = (√2/2)/(√2/2) = 1.",
    points: 30,
    timeLimit: 40,
    tags: ["trigonometry", "angles"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "What is 5! (factorial)?",
    options: ["120", "100", "60", "240"],
    answer: "120",
    explanation: "5! = 5 × 4 × 3 × 2 × 1 = 120.",
    points: 20,
    timeLimit: 30,
    tags: ["combinatorics", "factorial"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "MEDIUM",
    question: "If a triangle has angles 45°, 60°, and x°, what is x?",
    options: ["75°", "90°", "60°", "45°"],
    answer: "75°",
    explanation: "Sum of angles in a triangle = 180°. 45 + 60 + x = 180, so x = 75.",
    points: 20,
    timeLimit: 30,
    tags: ["geometry", "triangles"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is the smallest prime number?",
    options: ["2", "1", "3", "5"],
    answer: "2",
    explanation: "2 is the smallest prime number and the only even prime.",
    points: 10,
    timeLimit: 20,
    tags: ["number theory", "primes"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "HARD",
    question: "What is the probability of rolling two dice and getting a sum of 7?",
    options: ["1/6", "1/12", "1/36", "1/8"],
    answer: "1/6",
    explanation: "Possible outcomes: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 outcomes out of 36 total.",
    points: 30,
    timeLimit: 45,
    tags: ["probability", "statistics"],
  },
  {
    subject: "MATHEMATICS",
    difficulty: "EASY",
    question: "What is the GCD of 24 and 36?",
    options: ["12", "6", "18", "24"],
    answer: "12",
    explanation: "Greatest Common Divisor of 24 and 36 is 12.",
    points: 10,
    timeLimit: 20,
    tags: ["number theory", "divisibility"],
  },

  // ========== SCIENCE (20 QUESTIONS) ==========
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What is the chemical formula for water?",
    options: ["H₂O", "CO₂", "O₂", "H₂O₂"],
    answer: "H₂O",
    explanation: "Water consists of 2 hydrogen atoms bonded to 1 oxygen atom.",
    points: 10,
    timeLimit: 20,
    tags: ["chemistry", "basics"],
  },
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What planet is closest to the Sun?",
    options: ["Mercury", "Venus", "Earth", "Mars"],
    answer: "Mercury",
    explanation: "Mercury is the first planet from the Sun, at an average distance of ~57.9 million km.",
    points: 10,
    timeLimit: 20,
    tags: ["astronomy", "solar system"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the speed of light in a vacuum?",
    options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
    answer: "3 × 10⁸ m/s",
    explanation: "The speed of light (c) ≈ 299,792,458 m/s ≈ 3 × 10⁸ m/s.",
    points: 20,
    timeLimit: 30,
    tags: ["physics", "constants"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the powerhouse of the cell?",
    options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"],
    answer: "Mitochondria",
    explanation: "Mitochondria produce ATP (energy) through cellular respiration, earning them the nickname 'powerhouse of the cell'.",
    points: 20,
    timeLimit: 25,
    tags: ["biology", "cell biology"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What does the Heisenberg Uncertainty Principle state?",
    options: ["Δx·Δp ≥ ℏ/2", "E = mc²", "F = ma", "PV = nRT"],
    answer: "Δx·Δp ≥ ℏ/2",
    explanation: "Heisenberg's principle states that position and momentum cannot both be precisely measured simultaneously.",
    points: 40,
    timeLimit: 60,
    tags: ["quantum physics", "uncertainty"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What is the atomic number of Gold (Au)?",
    options: ["79", "78", "80", "47"],
    answer: "79",
    explanation: "Gold (Au) has atomic number 79, meaning it has 79 protons in its nucleus.",
    points: 35,
    timeLimit: 40,
    tags: ["chemistry", "periodic table"],
  },
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What gas do plants absorb from the atmosphere?",
    options: ["CO₂", "O₂", "N₂", "H₂"],
    answer: "CO₂",
    explanation: "Plants absorb carbon dioxide (CO₂) during photosynthesis to produce glucose and oxygen.",
    points: 10,
    timeLimit: 20,
    tags: ["biology", "photosynthesis"],
  },
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What is the chemical symbol for Sodium?",
    options: ["Na", "S", "So", "Sd"],
    answer: "Na",
    explanation: "Sodium's chemical symbol is Na, derived from its Latin name 'natrium'.",
    points: 10,
    timeLimit: 20,
    tags: ["chemistry", "elements"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the pH of a neutral solution?",
    options: ["7", "0", "14", "10"],
    answer: "7",
    explanation: "A neutral solution has a pH of 7. Values below 7 are acidic, above 7 are basic.",
    points: 20,
    timeLimit: 30,
    tags: ["chemistry", "acids and bases"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What is the SI unit of force?",
    options: ["Newton (N)", "Joule (J)", "Pascal (Pa)", "Watt (W)"],
    answer: "Newton (N)",
    explanation: "The Newton (N) is the SI unit of force, defined as the force needed to accelerate 1 kg at 1 m/s².",
    points: 20,
    timeLimit: 30,
    tags: ["physics", "mechanics"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What is the process by which water changes from liquid to gas?",
    options: ["Evaporation", "Condensation", "Sublimation", "Deposition"],
    answer: "Evaporation",
    explanation: "Evaporation is the process where liquid water turns into water vapor at the surface.",
    points: 30,
    timeLimit: 40,
    tags: ["physics", "thermodynamics"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What is Avogadro's number?",
    options: ["6.022 × 10²³", "6.022 × 10¹⁸", "3.14 × 10²³", "2.5 × 10²²"],
    answer: "6.022 × 10²³",
    explanation: "Avogadro's number (6.022 × 10²³) is the number of atoms/molecules in one mole of substance.",
    points: 30,
    timeLimit: 40,
    tags: ["chemistry", "molar mass"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What are the three states of matter?",
    options: ["Solid, Liquid, Gas", "Solid, Liquid, Plasma", "Hot, Cold, Neutral", "Solid, Liquid, Air"],
    answer: "Solid, Liquid, Gas",
    explanation: "The three fundamental states of matter are solid (fixed shape), liquid (fixed volume), and gas (no fixed shape or volume).",
    points: 20,
    timeLimit: 30,
    tags: ["physics", "matter"],
  },
  {
    subject: "SCIENCE",
    difficulty: "EASY",
    question: "What is the chemical formula for table salt?",
    options: ["NaCl", "KCl", "CaCl₂", "MgCl₂"],
    answer: "NaCl",
    explanation: "Sodium chloride (NaCl) is the chemical compound we commonly call table salt.",
    points: 10,
    timeLimit: 20,
    tags: ["chemistry", "compounds"],
  },
  {
    subject: "SCIENCE",
    difficulty: "MEDIUM",
    question: "What does X-ray wavelength range fall into?",
    options: ["0.01 to 10 nm", "100 to 1000 nm", "0.5 to 50 μm", "1 to 10 cm"],
    answer: "0.01 to 10 nm",
    explanation: "X-rays have wavelengths between 0.01 nm and 10 nm, falling between ultraviolet and gamma rays.",
    points: 20,
    timeLimit: 35,
    tags: ["physics", "radiation"],
  },
  {
    subject: "SCIENCE",
    difficulty: "HARD",
    question: "What is the second law of thermodynamics?",
    options: ["Entropy of universe always increases", "Energy is conserved", "Heat flows from hot to cold", "Work equals force times distance"],
    answer: "Entropy of universe always increases",
    explanation: "The second law states that the entropy (disorder) of a closed system always increases over time.",
    points: 30,
    timeLimit: 45,
    tags: ["physics", "thermodynamics"],
  },

  // ========== TECHNOLOGY (20 QUESTIONS) ==========
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does CPU stand for?",
    options: ["Central Processing Unit", "Computer Personal Unit", "Core Processing Unit", "Central Program Utility"],
    answer: "Central Processing Unit",
    explanation: "CPU (Central Processing Unit) is the primary component that executes instructions in a computer.",
    points: 10,
    timeLimit: 20,
    tags: ["hardware", "basics"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does HTML stand for?",
    options: ["HyperText Markup Language", "High-Level Text Machine Language", "HyperTransfer Markup Logic", "Home Tool Markup Language"],
    answer: "HyperText Markup Language",
    explanation: "HTML (HyperText Markup Language) is the standard language for creating web pages.",
    points: 10,
    timeLimit: 20,
    tags: ["web development", "basics"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is the time complexity of binary search on a sorted array?",
    options: ["O(log n)", "O(n)", "O(n²)", "O(1)"],
    answer: "O(log n)",
    explanation: "Binary search halves the search space at each step, resulting in O(log n) time complexity.",
    points: 20,
    timeLimit: 30,
    tags: ["algorithms", "complexity"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is the purpose of a REST API?",
    options: ["Enable communication between client and server", "Store data in a database", "Render HTML pages", "Compile code"],
    answer: "Enable communication between client and server",
    explanation: "REST APIs provide a standardized way for clients and servers to communicate using HTTP methods.",
    points: 20,
    timeLimit: 30,
    tags: ["web development", "APIs"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "In blockchain, what is a Merkle Tree used for?",
    options: ["Efficient verification of large data sets", "Mining new blocks", "Encrypting private keys", "Consensus mechanism"],
    answer: "Efficient verification of large data sets",
    explanation: "Merkle Trees create a hash-based tree structure allowing efficient and secure verification of data.",
    points: 35,
    timeLimit: 45,
    tags: ["blockchain", "data structures"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "What is the difference between TCP and UDP?",
    options: ["TCP is reliable/ordered; UDP is faster but unreliable", "TCP is faster; UDP is reliable", "They are the same protocol", "TCP is for web; UDP is for databases"],
    answer: "TCP is reliable/ordered; UDP is faster but unreliable",
    explanation: "TCP provides guaranteed delivery and ordering. UDP sacrifices reliability for speed, used in streaming/gaming.",
    points: 35,
    timeLimit: 45,
    tags: ["networking", "protocols"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does GUI stand for?",
    options: ["Graphical User Interface", "General Universal Interface", "Graphics Utility Interface", "graphing Utility Interface"],
    answer: "Graphical User Interface",
    explanation: "GUI (Graphical User Interface) is a type of user interface using graphics and visual elements.",
    points: 10,
    timeLimit: 20,
    tags: ["user interface", "basics"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What does JSON stand for?",
    options: ["JavaScript Object Notation", "Java Syntax Object Network", "Joint System Object Node", "JavaScript online Network"],
    answer: "JavaScript Object Notation",
    explanation: "JSON (JavaScript Object Notation) is a lightweight data interchange format widely used in APIs.",
    points: 10,
    timeLimit: 20,
    tags: ["data formats", "web"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is the primary purpose of a database index?",
    options: ["Improve query performance", "Reduce data storage", "Encrypt data", "Backup data automatically"],
    answer: "Improve query performance",
    explanation: "Database indexes speed up query searches by creating a sorted structure for faster lookups.",
    points: 20,
    timeLimit: 30,
    tags: ["databases", "optimization"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is OAuth used for?",
    options: ["Authorization and authentication", "Data encryption", "Network routing", "File compression"],
    answer: "Authorization and authentication",
    explanation: "OAuth is an open standard for authorization allowing users to authenticate without sharing passwords.",
    points: 20,
    timeLimit: 30,
    tags: ["security", "authentication"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "What is the time complexity of QuickSort in the worst case?",
    options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
    answer: "O(n²)",
    explanation: "QuickSort has O(n²) worst-case complexity when the pivot selection is poor, but O(n log n) average case.",
    points: 30,
    timeLimit: 40,
    tags: ["algorithms", "sorting"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "What is containerization used for?",
    options: ["Packaging applications with dependencies for consistency", "Compressing files", "Backing up data", "Encrypting files"],
    answer: "Packaging applications with dependencies for consistency",
    explanation: "Containerization (e.g., Docker) packages apps with all dependencies for consistent deployment across environments.",
    points: 30,
    timeLimit: 40,
    tags: ["devops", "containers"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What does CSS stand for?",
    options: ["Cascading Style Sheets", "Computer System Software", "Code Styling System", "Cascading Script Specification"],
    answer: "Cascading Style Sheets",
    explanation: "CSS (Cascading Style Sheets) is used to style and layout web pages in HTML.",
    points: 20,
    timeLimit: 30,
    tags: ["web development", "styles"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "EASY",
    question: "What is the function of a firewall?",
    options: ["Block unauthorized network traffic", "Boost internet speed", "Encrypt files", "Clean viruses"],
    answer: "Block unauthorized network traffic",
    explanation: "A firewall monitors and controls incoming and outgoing network traffic based on security rules.",
    points: 10,
    timeLimit: 20,
    tags: ["security", "networking"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "MEDIUM",
    question: "What is HTTPS primarily used for?",
    options: ["Secure communication over internet", "Faster data transfer", "Storing data", "Managing servers"],
    answer: "Secure communication over internet",
    explanation: "HTTPS (HTTP Secure) encrypts data in transit, protecting it from interception.",
    points: 20,
    timeLimit: 30,
    tags: ["security", "web"],
  },
  {
    subject: "TECHNOLOGY",
    difficulty: "HARD",
    question: "What is the CAP theorem in distributed systems?",
    options: ["Consistency, Availability, Partition tolerance (pick 2)", "Compute, Access, Performance", "Cache, Algorithm, Protocol", "Capacity, Availability, Parallel"],
    answer: "Consistency, Availability, Partition tolerance (pick 2)",
    explanation: "The CAP theorem states that distributed systems can only guarantee 2 of 3: consistency, availability, or partition tolerance.",
    points: 30,
    timeLimit: 45,
    tags: ["distributed systems", "theory"],
  },

  // ========== ENGINEERING (20 QUESTIONS) ==========
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "Ohm's Law states that V = ?",
    options: ["I × R", "I / R", "I + R", "I² × R"],
    answer: "I × R",
    explanation: "Ohm's Law: Voltage (V) = Current (I) × Resistance (R). Fundamental to electrical engineering.",
    points: 10,
    timeLimit: 20,
    tags: ["electrical", "fundamentals"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "What does CAD stand for in engineering?",
    options: ["Computer-Aided Design", "Computer Automated Drawing", "Central Application Design", "Computer Analysis Device"],
    answer: "Computer-Aided Design",
    explanation: "CAD (Computer-Aided Design) is software used to create 2D and 3D models of products and structures.",
    points: 10,
    timeLimit: 20,
    tags: ["design", "tools"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the SI unit of pressure?",
    options: ["Pascal (Pa)", "Newton (N)", "Joule (J)", "Watt (W)"],
    answer: "Pascal (Pa)",
    explanation: "The Pascal (Pa) is the SI unit of pressure, equal to 1 Newton per square meter (N/m²).",
    points: 20,
    timeLimit: 25,
    tags: ["mechanics", "units"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the purpose of a capacitor in a circuit?",
    options: ["Store and release electrical energy", "Resist current flow", "Amplify signals", "Convert AC to DC"],
    answer: "Store and release electrical energy",
    explanation: "Capacitors store electrical energy in an electric field and release it when needed.",
    points: 20,
    timeLimit: 30,
    tags: ["electrical", "components"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "What does the Nyquist theorem state in signal processing?",
    options: ["Sample rate must be at least 2× signal frequency", "Sample rate equals signal frequency", "Signal frequency must be halved", "Bandwidth equals sample rate"],
    answer: "Sample rate must be at least 2× signal frequency",
    explanation: "To accurately reconstruct a signal, the sampling rate must be at least twice the highest frequency present.",
    points: 35,
    timeLimit: 45,
    tags: ["signal processing", "digital"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "In materials science, what is Young's Modulus a measure of?",
    options: ["Material stiffness/elasticity", "Material hardness", "Thermal conductivity", "Electrical resistance"],
    answer: "Material stiffness/elasticity",
    explanation: "Young's Modulus (E) measures a material's stiffness — the ratio of stress to strain in the elastic region.",
    points: 35,
    timeLimit: 45,
    tags: ["materials science", "mechanics"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "What does PLC stand for in industrial automation?",
    options: ["Programmable Logic Controller", "Power Logic Circuit", "Processor Logic Control", "Platform Logic Code"],
    answer: "Programmable Logic Controller",
    explanation: "A PLC (Programmable Logic Controller) is an industrial computer that controls manufacturing processes.",
    points: 10,
    timeLimit: 20,
    tags: ["automation", "control"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "What is the SI unit of voltage?",
    options: ["Volt (V)", "Ampere (A)", "Ohm (Ω)", "Watt (W)"],
    answer: "Volt (V)",
    explanation: "The Volt (V) is the SI unit of electrical potential difference or electromotive force.",
    points: 10,
    timeLimit: 20,
    tags: ["electrical", "units"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the function of a transformer in electrical circuits?",
    options: ["Change voltage levels", "Regulate current", "Prevent power surges", "Store energy"],
    answer: "Change voltage levels",
    explanation: "Transformers convert electrical energy from one voltage level to another using electromagnetic induction.",
    points: 20,
    timeLimit: 30,
    tags: ["electrical", "power"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the definition of mechanical advantage?",
    options: ["Ratio of output force to input force", "Ratio of input power to output power", "Total force applied", "Machine efficiency percentage"],
    answer: "Ratio of output force to input force",
    explanation: "Mechanical advantage = effort force / load force, showing how much a machine amplifies applied force.",
    points: 20,
    timeLimit: 30,
    tags: ["mechanics", "machines"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "What is fatigue in materials engineering?",
    options: ["Progressive failure under cyclic stress", "Material degradation over time", "Deformation under load", "Surface corrosion"],
    answer: "Progressive failure under cyclic stress",
    explanation: "Material fatigue occurs when cyclic stresses cause progressive failure even below the yield strength.",
    points: 30,
    timeLimit: 40,
    tags: ["materials science", "mechanics"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "What is the Stefan-Boltzmann Law in heat transfer?",
    options: ["Radiant power proportional to T⁴", "Heat flow proportional to temperature difference", "Energy equals mass times c²", "Entropy increases in isolated systems"],
    answer: "Radiant power proportional to T⁴",
    explanation: "The Stefan-Boltzmann Law states that radiant energy emitted proportional to T⁴: P = εσAT⁴.",
    points: 30,
    timeLimit: 45,
    tags: ["thermodynamics", "heat transfer"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What is the primary function of a bearing in mechanical systems?",
    options: ["Reduce friction between moving parts", "Transmit torque", "Prevent vibration", "Dissipate heat"],
    answer: "Reduce friction between moving parts",
    explanation: "Bearings support and guide rotating parts while minimizing friction through rolling or sliding surfaces.",
    points: 20,
    timeLimit: 30,
    tags: ["mechanical", "components"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "EASY",
    question: "What is the definition of work in physics?",
    options: ["Force times distance in direction of force", "Energy per unit time", "Force per unit area", "Mass times acceleration"],
    answer: "Force times distance in direction of force",
    explanation: "Work (W) = Force (F) × Distance (d) × cos(θ), where θ is the angle between force and displacement.",
    points: 10,
    timeLimit: 20,
    tags: ["mechanics", "energy"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "MEDIUM",
    question: "What does HVAC stand for?",
    options: ["Heating, Ventilation, Air Conditioning", "High Voltage Alternating Current", "Hydraulic Vapor Air Control", "Heavy Variable Atmospheric Control"],
    answer: "Heating, Ventilation, Air Conditioning",
    explanation: "HVAC systems control temperature, humidity, and air quality in buildings.",
    points: 20,
    timeLimit: 30,
    tags: ["systems", "controls"],
  },
  {
    subject: "ENGINEERING",
    difficulty: "HARD",
    question: "What is the Euler-Bernoulli beam equation used for?",
    options: ["Predict deflection of beams under load", "Calculate structural strength", "Design columns", "Analyze buckling"],
    answer: "Predict deflection of beams under load",
    explanation: "The Euler-Bernoulli equation models beam deflection (y) as a function of applied loads and material properties.",
    points: 30,
    timeLimit: 45,
    tags: ["structural analysis", "mechanics"],
  },
];

const achievements = [
  {
    name: "First Steps",
    description: "Complete your first quiz",
    icon: "🎯",
    category: "SCORE",
    condition: { type: "quiz_count", value: 1 },
    xpReward: 50,
    coinsReward: 25,
    rarity: "COMMON",
  },
  {
    name: "Getting Started",
    description: "Complete 10 quizzes",
    icon: "📚",
    category: "SCORE",
    condition: { type: "quiz_count", value: 10 },
    xpReward: 100,
    coinsReward: 50,
    rarity: "COMMON",
  },
  {
    name: "Math Wizard",
    description: "Score 100% on 5 Math quizzes",
    icon: "🧮",
    category: "SUBJECT_MASTERY",
    condition: { type: "perfect_score", value: 5, subject: "MATHEMATICS" },
    xpReward: 200,
    coinsReward: 100,
    rarity: "RARE",
  },
  {
    name: "Science Genius",
    description: "Score 100% on 5 Science quizzes",
    icon: "🔬",
    category: "SUBJECT_MASTERY",
    condition: { type: "perfect_score", value: 5, subject: "SCIENCE" },
    xpReward: 200,
    coinsReward: 100,
    rarity: "RARE",
  },
  {
    name: "On Fire 🔥",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    category: "STREAK",
    condition: { type: "streak", value: 7 },
    xpReward: 300,
    coinsReward: 150,
    rarity: "EPIC",
  },
  {
    name: "Speed Demon",
    description: "Answer a question in under 5 seconds",
    icon: "⚡",
    category: "SPEED",
    condition: { type: "fast_answer", value: 5 },
    xpReward: 150,
    coinsReward: 75,
    rarity: "RARE",
  },
  {
    name: "STEM Legend",
    description: "Reach level 20",
    icon: "👑",
    category: "SPECIAL",
    condition: { type: "level", value: 20 },
    xpReward: 1000,
    coinsReward: 500,
    rarity: "LEGENDARY",
  },
  {
    name: "All-Rounder",
    description: "Play quizzes in all 4 STEM subjects",
    icon: "🌟",
    category: "SPECIAL",
    condition: { type: "all_subjects", value: 4 },
    xpReward: 250,
    coinsReward: 125,
    rarity: "EPIC",
  },
];

async function main() {
  console.log("🌱 Seeding STEMiks database...");

  // Clear existing questions to avoid duplicates
  await prisma.question.deleteMany({});

  for (const q of questions) {
    await prisma.question.create({ data: q as any });
  }
  console.log(`✅ Seeded ${questions.length} questions`);

  for (const a of achievements) {
    await prisma.achievement.upsert({
      where: { name: a.name },
      update: {},
      create: a as any,
    });
  }
  console.log(`✅ Seeded ${achievements.length} achievements`);
  console.log("🎉 Database seed complete!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
